name: item-shippoint
kind: autocomplete
task_type: multiclass_classification
description: Predict the `SHIPPINGPOINT` column of the `salesdocumentitem` table.
entity_table: salesdocumentitem
target_col: SHIPPINGPOINT
remove_columns:
- - salesdocument
  - SALESOFFICE
- - salesdocument
  - SALESGROUP
- - salesdocument
  - CUSTOMERPAYMENTTERMS
- - salesdocument
  - SHIPPINGCONDITION
- - salesdocument
  - HEADERINCOTERMSCLASSIFICATION
- - salesdocumentitem
  - PLANT
- - salesdocumentitem
  - ITEMINCOTERMSCLASSIFICATION
manifest_version: 1
