name: site-sponsor-run
kind: forecast
task_type: link_prediction
description: Predict whether this sponsor will have a trial in a facility.
target_col: sponsor_id
time_col: timestamp
src_entity_table: facilities
src_entity_col: facility_id
dst_entity_table: sponsors
dst_entity_col: sponsor_id
eval_k: 10
timedelta: 365 days
sql: |-
  SELECT
      t.timestamp,
      fs.facility_id,
      LIST(DISTINCT ss.sponsor_id) AS sponsor_id
  FROM timestamps t
  LEFT JOIN facilities_studies fs
  LEFT JOIN sponsors_studies ss ON ss.nct_id = fs.nct_id
  ON fs.date > t.timestamp
      and fs.date <= t.timestamp + INTERVAL '{timedelta}'
  GROUP BY t.timestamp, fs.facility_id;
manifest_version: 1
