name: user-ad-visit
kind: forecast
task_type: link_prediction
description: Predict the distinct list of ads a user will visit in the next 4 days.
time_col: timestamp
src_entity_table: UserInfo
src_entity_col: UserID
dst_entity_table: AdsInfo
dst_entity_col: AdID
eval_k: 12
timedelta: 4 days
sql: "\n            SELECT\n                visit_ads.UserID,\n                t.timestamp,\n                LIST(DISTINCT visit_ads.AdID) AS AdID,\n            FROM\n                timestamps t\n            LEFT JOIN\n            (\n                    UserInfo\n                LEFT JOIN\n                    VisitStream\n                ON\n                    UserInfo.UserID == VisitStream.UserID\n            ) visit_ads\n            ON\n                visit_ads.ViewDate > t.timestamp AND\n                visit_ads.ViewDate <= t.timestamp + INTERVAL '{timedelta}'\n            GROUP BY\n                t.timestamp,\n                visit_ads.UserID\n            "
manifest_version: 1
