name: item-sales
kind: forecast
task_type: regression
description: Predict the total sales for an article (the sum of prices of the associated transactions) in the next week.
entity_table: article
entity_col: article_id
target_col: sales
time_col: timestamp
timedelta: 7 days
sql: "\n            SELECT\n                timestamp,\n                article_id,\n                sales\n            FROM\n                timestamps,\n                article,\n                (\n                    SELECT\n                        COALESCE(SUM(price), 0) as sales\n                    FROM\n                        transactions,\n                    WHERE\n                        transactions.article_id = article.article_id AND\n                        t_dat > timestamp AND\n                        t_dat <= timestamp + INTERVAL '{timedelta}'\n                )\n            "
manifest_version: 1
