name: user-item-rate
kind: forecast
task_type: link_prediction
description: Predict the list of distinct items each customer will purchase and give a 5 star review in the next two years.
target_col: product_id
time_col: timestamp
src_entity_table: customer
src_entity_col: customer_id
dst_entity_table: product
dst_entity_col: product_id
eval_k: 10
timedelta: 91 days
sql: "\n                SELECT\n                    t.timestamp,\n                    review.customer_id,\n                    LIST(DISTINCT review.product_id) AS product_id\n                FROM\n                    timestamps t\n                LEFT JOIN\n                    review\n                ON\n                    review.review_time > t.timestamp AND\n                    review.review_time <= t.timestamp + INTERVAL '{timedelta}'\n                WHERE\n                    review.customer_id IS NOT NULL\n                    AND review.product_id IS NOT NULL\n                    AND review.rating = 5.0\n                GROUP BY\n                    t.timestamp,\n                    review.customer_id\n            "
manifest_version: 1
