name: paper-paper-cocitation
kind: forecast
task_type: link_prediction
description: Predict which other papers will be cited together with a given paper in the next six months.
target_col: co_cited
time_col: date
src_entity_table: papers
src_entity_col: Paper_ID
dst_entity_table: papers
dst_entity_col: co_cited
eval_k: 10
timedelta: 182 days
sql: "\n            WITH paper_co_citations AS (\n                SELECT\n                    t.timestamp AS date,\n                    p.Paper_ID,\n                    c2.References_Paper_ID AS co_cited_paper\n                FROM timestamps t\n                JOIN papers p\n                  ON p.Submission_Date <= t.timestamp\n                JOIN citations c1\n                  ON c1.References_Paper_ID = p.Paper_ID\n                  AND c1.Submission_Date > t.timestamp\n                  AND c1.Submission_Date <= t.timestamp + INTERVAL '{timedelta}'\n                JOIN citations c2\n                  ON c1.Paper_ID = c2.Paper_ID\n                  AND c2.References_Paper_ID <> p.Paper_ID\n                  AND c2.Submission_Date > t.timestamp\n                  AND c2.Submission_Date <= t.timestamp + INTERVAL '{timedelta}'\n            )\n            SELECT\n                date,\n                Paper_ID,\n                array_agg(DISTINCT co_cited_paper) AS co_cited\n            FROM paper_co_citations\n            GROUP BY date, Paper_ID\n            ;\n            "
manifest_version: 1
