name: user-item-purchase
kind: forecast
task_type: link_prediction
description: Predict the list of articles each customer will purchase in the next seven days.
target_col: article_id
time_col: timestamp
src_entity_table: customer
src_entity_col: customer_id
dst_entity_table: article
dst_entity_col: article_id
eval_k: 12
timedelta: 7 days
sql: "\n            SELECT\n                t.timestamp,\n                transactions.customer_id,\n                LIST(DISTINCT transactions.article_id) AS article_id\n            FROM\n                timestamps t\n            LEFT JOIN\n                transactions\n            ON\n                transactions.t_dat > t.timestamp AND\n                transactions.t_dat <= t.timestamp + INTERVAL '{timedelta}'\n            GROUP BY\n                t.timestamp,\n                transactions.customer_id\n            "
manifest_version: 1
