name: driver-circuit-compete
kind: forecast
task_type: link_prediction
description: Predict which circuits a driver will compete on in the next year.
target_col: circuitId
time_col: date
src_entity_table: drivers
src_entity_col: driverId
dst_entity_table: circuits
dst_entity_col: circuitId
eval_k: 10
timedelta: 365 days
sql: |-
  SELECT
      t.timestamp as date,
      re.driverId as driverId,
      LIST(DISTINCT race.circuitId) as circuitId
  FROM
      timestamps t
  LEFT JOIN
      races race
  ON
      race.date <= t.timestamp + INTERVAL '{timedelta}'
      and race.date > t.timestamp
  LEFT JOIN
      results re
  ON
      re.raceId = race.raceId
  GROUP BY t.timestamp, re.driverId
manifest_version: 1
