name: eligibilities-child
kind: autocomplete
task_type: binary_classification
description: Predict the `child` column of the `eligibilities` table.
entity_table: eligibilities
target_col: child
remove_columns:
- - eligibilities
  - adult
- - eligibilities
  - older_adult
- - eligibilities
  - minimum_age
- - eligibilities
  - maximum_age
- - eligibilities
  - population
- - eligibilities
  - criteria
- - eligibilities
  - gender_description
manifest_version: 1
