name: user-ltv
kind: forecast
task_type: regression
description: LTV (life-time value) for a customer is the sum of prices of products that the customer reviews in the time window.
entity_table: customer
entity_col: customer_id
target_col: ltv
time_col: timestamp
timedelta: 91 days
sql: "\n            SELECT\n                timestamp,\n                customer_id,\n                ltv,\n            FROM\n                timestamps,\n                customer,\n                (\n                    SELECT\n                        COALESCE(SUM(price), 0) as ltv,\n                    FROM\n                        review,\n                        product\n                    WHERE\n                        review.customer_id = customer.customer_id AND\n                        review.product_id = product.product_id AND\n                        review_time > timestamp AND\n                        review_time <= timestamp + INTERVAL '{timedelta}'\n                )\n            WHERE\n                EXISTS (\n                    SELECT 1\n                    FROM review\n                    WHERE\n                        review.customer_id = customer.customer_id AND\n                        review_time > timestamp - INTERVAL '{timedelta}' AND\n                        review_time <= timestamp\n                )\n            "
manifest_version: 1
