name: item-ltv
kind: forecast
task_type: regression
description: LTV (life-time value) for a product is the numer of times the product is purchased in the time window multiplied by price.
entity_table: product
entity_col: product_id
target_col: ltv
time_col: timestamp
timedelta: 91 days
sql: "\n            SELECT\n                timestamp,\n                product.product_id,\n                COALESCE(SUM(price), 0) AS ltv,\n            FROM\n                timestamps,\n                product,\n                review\n            WHERE\n                review.product_id = product.product_id AND\n                review_time > timestamp AND\n                review_time <= timestamp + INTERVAL '{timedelta}'\n            GROUP BY\n                timestamp,\n                product.product_id\n            "
manifest_version: 1
