name: user-beer-favorite
kind: external
task_type: link_prediction
description: Predict the list of distinct beers each active user will add to their favorites in the next 90 days.
target_col: beer_id
time_col: timestamp
src_entity_table: users
src_entity_col: user_id
dst_entity_table: beers
dst_entity_col: beer_id
eval_k: 10
timedelta: 90 days
sql: "\n            SELECT\n                t.timestamp,\n                f.user_id,\n                LIST(DISTINCT f.beer_id) AS beer_id\n            FROM\n                timestamps t\n            LEFT JOIN\n                favorites as f\n            ON\n                f.created_at > t.timestamp AND\n                f.created_at <= t.timestamp + INTERVAL '{timedelta}'\n            WHERE\n                f.user_id is not null and f.beer_id is not null\n                AND EXISTS (\n                    SELECT 1\n                    FROM beer_ratings as br\n                    WHERE br.user_id = f.user_id\n                    AND br.created_at > t.timestamp - INTERVAL '{timedelta}'\n                    AND br.created_at <= t.timestamp\n                )\n            GROUP BY\n                t.timestamp,\n                f.user_id\n            "
manifest_version: 1
