name: post-votes
kind: forecast
task_type: regression
description: Predict the number of upvotes that an existing question will receive in the next 2 years.
entity_table: posts
entity_col: PostId
target_col: popularity
time_col: timestamp
timedelta: 91 days
sql: "\n            SELECT\n                t.timestamp,\n                p.id AS PostId,\n                COUNT(distinct v.id) AS popularity\n            FROM\n                timestamps t\n            LEFT JOIN\n                posts p\n            ON\n                p.CreationDate <= t.timestamp AND\n                p.owneruserid != -1 AND\n                p.owneruserid is not null AND\n                p.PostTypeId = 1\n            LEFT JOIN\n                votes v\n            ON\n                p.id = v.PostId AND\n                v.CreationDate > t.timestamp AND\n                v.CreationDate <= t.timestamp + INTERVAL '{timedelta}' AND\n                v.votetypeid = 2\n            GROUP BY\n                t.timestamp,\n                p.id\n            ;\n\n            "
manifest_version: 1
