name: user-badge
kind: forecast
task_type: binary_classification
description: Predict if each user will receive in a new badge the next 2 years.
entity_table: users
entity_col: UserId
target_col: WillGetBadge
time_col: timestamp
timedelta: 91 days
sql: "\n            SELECT\n                timestamp,\n                CAST(UserId AS BIGINT) AS UserId,\n                WillGetBadge\n            FROM (\n            SELECT\n                t.timestamp,\n                u.Id as UserId,\n            CASE WHEN\n                COUNT(b.Id) >= 1 THEN 1 ELSE 0 END AS WillGetBadge\n            FROM\n                timestamps t\n            LEFT JOIN\n                users u\n            ON\n                u.CreationDate <= t.timestamp\n            LEFT JOIN\n                badges b\n            ON\n                u.Id = b.UserID\n                AND b.Date > t.timestamp\n                AND b.Date <= t.timestamp + INTERVAL '{timedelta}'\n            GROUP BY\n                t.timestamp,\n                u.Id\n            )\n            WHERE UserId IS NOT NULL\n            "
manifest_version: 1
