name: badges-class
kind: autocomplete
task_type: multiclass_classification
description: Predict the `Class` column of the `badges` table.
entity_table: badges
target_col: Class
remove_columns:
- - badges
  - TagBased
- - badges
  - Name
manifest_version: 1
