r"""Publish a locally generated ``dbinfer`` collection to its Hugging Face repo.

    python provenance/push_dbinfer.py BUILD_DIR                 # dry run: show the plan
    python provenance/push_dbinfer.py BUILD_DIR --push          # upload
    python provenance/push_dbinfer.py BUILD_DIR --push --repo stanford-star/dbinfer
    python provenance/push_dbinfer.py BUILD_DIR --push --cards-only  # just the READMEs

``BUILD_DIR`` is the output of ``provenance/dbinfer.py --all`` (a directory of
``dbinfer-<name>/`` folders), optionally also holding the repo-level ``README.md`` and a
``STATS/`` folder.

The upload is a single commit that **replaces** every ``dbinfer-*`` path, so tables and
diagrams that no longer exist are removed rather than left behind. ``STATS/`` and the
repo ``README.md`` are overwritten when present in ``BUILD_DIR`` and left untouched
otherwise.

``--cards-only`` uploads just the dataset cards and the repo card, with no deletions --
for refreshing prose without re-pushing gigabytes of unchanged parquet.
"""

from __future__ import annotations

import sys
from pathlib import Path

DEFAULT_REPO = "stanford-star/dbinfer"


def plan(build: Path) -> tuple[list, list]:
    datasets = sorted(p.parent for p in build.glob("dbinfer-*/manifest.yaml"))
    if not datasets:
        sys.exit(f"no dbinfer-*/manifest.yaml under {build}")
    extras = [p for p in (build / "README.md", build / "STATS") if p.exists()]
    return datasets, extras


def main(argv: list) -> int:
    if not argv:
        sys.exit(__doc__)
    build = Path(argv[0])
    do_push = "--push" in argv
    cards_only = "--cards-only" in argv
    repo = DEFAULT_REPO
    if "--repo" in argv:
        repo = argv[argv.index("--repo") + 1]

    datasets, extras = plan(build)
    total = 0
    print(f"repo: {repo}\nbuild: {build}\n")
    if cards_only:
        cards = [d / "README.md" for d in datasets if (d / "README.md").exists()]
        if (build / "README.md").exists():
            cards.append(build / "README.md")
        for p in cards:
            print(f"  {p.relative_to(build)}")
        print(f"\n  {len(cards)} card(s), no deletions")
    else:
        for d in datasets:
            files = [p for p in d.rglob("*") if p.is_file()]
            size = sum(p.stat().st_size for p in files)
            total += size
            print(f"  {d.name:26} {len(files):>4} files  {size / 2**30:>8.3f} GiB")
        for p in extras:
            print(f"  {p.name:26} {'(dir)' if p.is_dir() else '(file)'}")
        print(f"\n  total {total / 2**30:.3f} GiB")

    if not do_push:
        print("\ndry run -- pass --push to upload")
        return 0

    from huggingface_hub import HfApi

    api = HfApi()
    if cards_only:
        api.upload_folder(
            repo_id=repo,
            repo_type="dataset",
            folder_path=str(build),
            allow_patterns=["dbinfer-*/README.md", "README.md"],
            commit_message="Refresh dataset cards",
        )
        print(f"\npushed cards to https://huggingface.co/datasets/{repo}")
        return 0
    api.upload_folder(
        repo_id=repo,
        repo_type="dataset",
        folder_path=str(build),
        allow_patterns=["dbinfer-*/**", "STATS/**", "README.md"],
        # Replace the dataset folders wholesale: a table dropped by a regenerate must not
        # survive as a stale parquet.
        delete_patterns=["dbinfer-*/**"],
        commit_message="Rebuild dbinfer from the original 4DBInfer archives",
        commit_description=(
            "Regenerated by provenance/dbinfer.py from "
            "https://data.dgl.ai/mtbench/20240304-<name>.tar (sha256-pinned), replacing "
            "the port derived from dbinfer-relbench-adapter's db.zip artifacts.\n\n"
            "Fixes: foreign keys were 99.9-100% null (validated against the parent's "
            "column count); real primary keys were overwritten before that validation; "
            "foreign keys to non-materialized key domains were dropped; task entity ids "
            "used a task-local remapping unrelated to the database's; task time columns "
            "were cast from integers into 1970 timestamps; classification targets were "
            "relabelled by sorted-string order and task_type inferred from cardinality; "
            "undeclared label and full-history-aggregate columns were published.\n\n"
            "Results computed against the previous revision are not comparable."
        ),
    )
    print(f"\npushed to https://huggingface.co/datasets/{repo}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
