name: user-churn
kind: forecast
task_type: binary_classification
description: Predict the churn for a customer (no transactions) in the next week.
entity_table: customer
entity_col: customer_id
target_col: churn
time_col: timestamp
timedelta: 7 days
sql: "\n            SELECT\n                timestamp,\n                customer_id,\n                CAST(\n                    NOT EXISTS (\n                        SELECT 1\n                        FROM transactions\n                        WHERE\n                            transactions.customer_id = customer.customer_id AND\n                            t_dat > timestamp AND\n                            t_dat <= timestamp + INTERVAL '{timedelta}'\n                    ) AS INTEGER\n                ) AS churn\n            FROM\n                timestamps,\n                customer,\n            WHERE\n                EXISTS (\n                    SELECT 1\n                    FROM transactions\n                    WHERE\n                        transactions.customer_id = customer.customer_id AND\n                        t_dat > timestamp - INTERVAL '{timedelta}' AND\n                        t_dat <= timestamp\n                )\n            "
manifest_version: 1
