name: user-attendance
kind: forecast
task_type: regression
description: Predict the number of events a user will go to in the next seven days 7 days.
entity_table: users
entity_col: user
target_col: target
time_col: timestamp
timedelta: 7 days
sql: "SELECT\n                t.timestamp,\n                CAST(event_attendees.user_id AS BIGINT) AS user,\n                SUM(CASE WHEN event_attendees.status IN ('yes', 'maybe') THEN 1 ELSE 0 END) AS target\n            FROM\n                timestamps t\n            LEFT JOIN\n                event_attendees\n            ON\n                event_attendees.start_time > t.timestamp AND\n                event_attendees.start_time <= t.timestamp + INTERVAL '{timedelta}'\n            WHERE\n                event_attendees.user_id IS NOT NULL\n            GROUP BY\n                t.timestamp,\n                event_attendees.user_id\n            "
manifest_version: 1
