name: sales-office
kind: autocomplete
task_type: multiclass_classification
description: Predict the `SALESOFFICE` column of the `salesdocument` table.
entity_table: salesdocument
target_col: SALESOFFICE
remove_columns:
- - salesdocument
  - SALESGROUP
- - salesdocument
  - CUSTOMERPAYMENTTERMS
- - salesdocument
  - SHIPPINGCONDITION
- - salesdocument
  - HEADERINCOTERMSCLASSIFICATION
- - salesdocumentitem
  - PLANT
- - salesdocumentitem
  - SHIPPINGPOINT
- - salesdocumentitem
  - ITEMINCOTERMSCLASSIFICATION
manifest_version: 1
