name: user-clicks
kind: forecast
task_type: binary_classification
description: Predict whether the each customer will click on more than one ads in the next 4 days.
entity_table: UserInfo
entity_col: UserID
target_col: num_click
time_col: timestamp
timedelta: 4 days
sql: "\n            SELECT\n                search_ads.UserID,\n                t.timestamp,\n                COALESCE(COUNT(search_ads.AdID), 0) > 1 AS num_click\n            FROM\n                timestamps t\n            LEFT JOIN\n            (\n                (\n                    UserInfo\n                        LEFT JOIN\n                    SearchInfo\n                        ON\n                    UserInfo.UserID == SearchInfo.UserID\n                ) user_search_info\n                LEFT JOIN\n                    SearchStream\n                ON\n                    user_search_info.SearchID == SearchStream.SearchID AND\n                    SearchStream.IsClick == 1.0\n            ) search_ads\n            ON\n                search_ads.SearchDate > t.timestamp AND\n                search_ads.SearchDate <= t.timestamp + INTERVAL '{timedelta}'\n            GROUP BY\n                t.timestamp,\n                search_ads.UserID\n            "
manifest_version: 1
