name: paper-citation
kind: forecast
task_type: binary_classification
description: Predict if a paper gets cited in the next 6 months.
entity_table: papers
entity_col: Paper_ID
target_col: cited
time_col: date
timedelta: 182 days
sql: "\n            WITH paper_citations AS (\n                SELECT\n                    t.timestamp AS date,\n                    p.Paper_ID,\n                    COUNT(c.References_Paper_ID) AS citation_count\n                FROM timestamps t\n                JOIN papers p\n                    ON p.Submission_Date <= t.timestamp\n                LEFT JOIN citations c\n                    ON c.References_Paper_ID = p.Paper_ID\n                    AND c.Submission_Date > t.timestamp\n                    AND c.Submission_Date <= t.timestamp + INTERVAL '{timedelta}'\n                GROUP BY t.timestamp, p.Paper_ID\n            )\n            SELECT\n                date,\n                Paper_ID,\n                CASE WHEN citation_count > 0 THEN 1 ELSE 0 END AS cited\n            FROM paper_citations;\n            "
manifest_version: 1
